const mongodb = require('mongodb');
const MongoClient = mongodb.MongoClient;

const products=[
{
	"category1" : "Normal Dishes",
	"category2" : "Breakfast",
	"category3" : "veg",
	"name" : "Idli + vada combo",
	"description" : "Idli is a type of savoury rice cake, originating from the Indian subcontinent, The cakes are made by steaming a batter consisting of fermented black lentils (de-husked) and rice.",
	"description2" : "This is an Indian Dish",
	"price" : 3.9,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fres.cloudinary.com%2Fswiggy%2Fimage%2Fupload%2Ffl_lossy%2Cf_auto%2Cq_auto%2Cw_508%2Ch_320%2Cc_fill%2Fwiyxmeviesaczslplnrq&imgrefurl=https%3A%2F%2Fwww.swiggy.com%2Frestaurants%2Fmr-and-mrs-idli-sector-15-fbd-faridabad-65211&tbnid=bn_Quu-Q04iD3M&vet=12ahUKEwja3OmZovHtAhX4AbcAHUGuDfQQMygDegUIARDDAQ..i&docid=v6BRihSn6wsQhM&w=508&h=320&q=pics%20of%20idli%20combo&ved=2ahUKEwja3OmZovHtAhX4AbcAHUGuDfQQMygDegUIARDDAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Breakfast",
	"category3" : "veg",
	"name" : "Rava Dosa Combo",
	"description" : "Rava dosa is a popular variety of South Indian dosa which are crisp, netted and thin. They are very easy to make and need no grinding or fermentation.",
	"description2" : "This is an Indian Dish",
	"price" : 4.0 ,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn1.foodviva.com%2Fstatic-content%2Ffood-images%2Fsouth-indian-recipes%2Frava-dosa%2Frava-dosa.jpg&imgrefurl=https%3A%2F%2Ffoodviva.com%2Fsouth-indian-recipes%2Frava-dosa%2F&tbnid=--uxX4glq9doRM&vet=12ahUKEwjF3YG9o_HtAhVKQn0KHU56CH0QMygEegUIARD5AQ..i&docid=aLLRELoHOuA4RM&w=500&h=650&q=pics%20of%20rava%20dosa&ved=2ahUKEwjF3YG9o_HtAhVKQn0KHU56CH0QMygEegUIARD5AQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Breakfast",
	"category3" : "veg",
	"name" : "Pongal Combo",
	"description" : "Pongal is a rich combination of rice, dal, ghee and dry fruits which makes our mouth water. It is a comfort food which can be prepared very easily",
	"description2" : "This is an Indian Dish",
	"price" : 4.1 ,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.indianhealthyrecipes.com%2Fwp-content%2Fuploads%2F2014%2F09%2Fven-pongal-recipe.jpg&imgrefurl=https%3A%2F%2Fwww.indianhealthyrecipes.com%2Fpongal-recipe-venn-pongal%2F&tbnid=pkDzgFijOm02DM&vet=12ahUKEwjo7Ii0pfHtAhXlBrcAHXqGDo4QMygAegUIARDhAQ..i&docid=re6ujsezbC-p_M&w=680&h=510&q=pics%20of%20ven%20pongal&ved=2ahUKEwjo7Ii0pfHtAhXlBrcAHXqGDo4QMygAegUIARDhAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Breakfast",
	"category3" : "veg",
	"name" : "Poori Combo ( Poori with Masala )",
	"description" : "Poori is a deep-fat fried bread made from unleavened whole-wheat flour that originated in the Indian subcontinent. It is eaten for Breakfast or as a snack or light meal. It is usually served with a curry or bhaji",
	"description2" : "This is an Indian Dish",
	"price" : 4.4 ,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ndtvimg.com%2Fi%2F2015-10%2Fpoori_625x350_61444805756.jpg&imgrefurl=https%3A%2F%2Ffood.ndtv.com%2Fhindi%2Ftry-these-five-best-poori-recipes-2052065&tbnid=dRVJridHpni8hM&vet=12ahUKEwi6vPngp_HtAhUXGHIKHX_aCEAQMygBegQIARBN..i&docid=A3w1szB3NtExaM&w=625&h=350&q=pics%20of%20ven%20poori&ved=2ahUKEwi6vPngp_HtAhUXGHIKHX_aCEAQMygBegQIARBN",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Breakfast",
	"category3" : "veg",
	"name" : "Kichadi",
	"description" : "Khichdi is a dish made of rice and lentils. In Indian culture, it is considered one of the first solid foods that babies eat. Khichdi was the inspiration for the Anglo-Indian dish kedgeree.",
	"description2" : "This is an Indian Dish",
	"price" : 3.5 ,
	"mediaUrl" : "#",
},

{
	"category1" : "Normal Dishes",
	"category2" : "Lunch",
	"category3" : "veg",
	"name" : "Bisibelabath with poriyal Veg",
	"description" : "Bisibelabath is a spicy, rice-based dish with origins in the state of Karnataka, India. It is said to have originated in the Mysore Palace and from there spread across the state of Karnataka",
	"description2" : "This is an Indian Dish",
	"price" : 4.2,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.indianveggiedelight.com%2Fwp-content%2Fuploads%2F2020%2F06%2Fbisibelebath.jpg&imgrefurl=https%3A%2F%2Fwww.indianveggiedelight.com%2Finstant-pot-bisibelebath%2F&tbnid=Ixz8LKGsJ-tYdM&vet=12ahUKEwiq98SfrPHtAhU0NHIKHZECAP0QMygAegUIARCyAQ..i&docid=sGcf3JHEnFSjKM&w=1024&h=1365&q=pics%20of%20bisibelebath&ved=2ahUKEwiq98SfrPHtAhU0NHIKHZECAP0QMygAegUIARCyAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Lunch",
	"category3" : "veg",
	"name" : "Veg Pulao",
	"description" : "Veg pulao is a spicy rice dish prepared by cooking rice with various vegetables and spices. The uniqueness of this recipe lies in use of bay leaf, cinnamon.",
	"description2" : "This is an Indian Dish",
	"price" : 4.1,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn1.foodviva.com%2Fstatic-content%2Ffood-images%2Frice-recipes%2Fvegetable-pulav-recipe%2Fvegetable-pulav-recipe.jpg&imgrefurl=https%3A%2F%2Ffoodviva.com%2Frice-recipes%2Fvegetable-pulav-recipe%2F&tbnid=gaeFuZDR4ut3JM&vet=12ahUKEwiX_oWCrvHtAhVSNHIKHWCGDO0QMygIegUIARCPAg..i&docid=HagzPNOsJ-7b1M&w=500&h=500&q=pics%20of%20veg%20pulao&ved=2ahUKEwiX_oWCrvHtAhVSNHIKHWCGDO0QMygIegUIARCPAg",
},{
	"category1" : "Normal Dishes",
	"category2" : "Lunch",
	"category3" : "nonveg",
	"name" : "Chicken Fried Rice",
	"description" : "Chicken fried rice is the comfort dish of Chinese food. The dish started as a way to use leftover fried rice that has dried out. The addition of oil and soy sauce and veggies and meat spruce up the rice for a delicious meal.",
	"description2" : "This is an Indian Dish",
	"price" : 4.5,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.funfoodfrolic.com%2Fwp-content%2Fuploads%2F2020%2F07%2FFried-Rice-Thumbnail.jpg&imgrefurl=https%3A%2F%2Fwww.funfoodfrolic.com%2Fchicken-fried-rice%2F&tbnid=knZmgjaifsi9nM&vet=12ahUKEwj71ra5r_HtAhXuk0sFHcgvAD8QMygDegUIARCIAg..i&docid=PsGFWI3lx7LwzM&w=1200&h=1200&q=pics%20of%20chicken%20fried%20rice&ved=2ahUKEwj71ra5r_HtAhXuk0sFHcgvAD8QMygDegUIARCIAg",
},{
	"category1" : "Normal Dishes",
	"category2" : "Lunch",
	"category3" : "veg",
	"name" : "Paneer Fried Rice",
	"description" : "A quick delicious rice dish that goes good in Lunch box. The recipe is an extension to the popular veg fried rice with a topping of marinated paneer cubes.",
	"description2" : "This is an Indian Dish",
	"price" : 4.4,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmuthuhealthyrecipes.com%2Fwp-content%2Fuploads%2F2020%2F07%2FSchezwan-Paneer-Fried-Rice-Recipe-260x195.jpg&imgrefurl=https%3A%2F%2Fmuthuhealthyrecipes.com%2Fschezwan-paneer-fried-rice%2F&tbnid=zj7lyApAP4ofPM&vet=12ahUKEwj6tYi2sPHtAhWhnksFHWtYC4oQMygsegUIARDaAg..i&docid=NgkrsUJmNeNrPM&w=260&h=195&q=pics%20of%20paneer%20fried%20rice&ved=2ahUKEwj6tYi2sPHtAhWhnksFHWtYC4oQMygsegUIARDaAg",
},{
	"category1" : "Normal Dishes",
	"category2" : "Lunch",
	"category3" : "nonveg",
	"name" : "Roti + Butter Chicken masala",
	"description" : "Butter chicken curry or murgh makhani is a curry of chicken in a spiced tomato, butter and cream sauce. The curry was made by chance by mixing leftover chicken in a tomato gravy, rich in butter and cream.",
	"description2" : "This is an Indian Dish",
	"price" : 4.5,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F53205522.cms%3Fimgsize%3D302803%26width%3D800%26height%3D800&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fbutter-chicken%2Frs53205522.cms&tbnid=x0erbBFQnpri4M&vet=12ahUKEwiP_eHEsfHtAhXDwHMBHf6ZAHEQMygAegUIARDuAQ..i&docid=gn80RtjETPAjDM&w=800&h=800&q=pics%20of%20butter%20chicken%20masala&ved=2ahUKEwiP_eHEsfHtAhXDwHMBHf6ZAHEQMygAegUIARDuAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Lunch",
	"category3" : "veg",
	"name" : "Roti + Paneer Butter masala",
	"description" : "Paneer Butter Masala is a slightly sweet creamy dish of paneer, originating from the Indian subcontinent, in which the gravy is prepared usually with butter, tomatoes, cashews or cream. Spices such as red chili powder and garam masala are also used to prepare this gravy.",
	"description2" : "This is an Indian Dish",
	"price" : 4.6,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F53098531.cms%3Fimgsize%3D246555%26width%3D800%26height%3D800&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fpaneer-butter-masala%2Frs53098531.cms&tbnid=muccZsp_Hi5T0M&vet=12ahUKEwiFvrHgsvHtAhW0n0sFHYq0Aa0QMygCegUIARD6AQ..i&docid=4yclBcIM-hT_OM&w=800&h=800&q=pics%20of%20paneer%20butter%20masala&ved=2ahUKEwiFvrHgsvHtAhW0n0sFHYq0Aa0QMygCegUIARD6AQ",
},

{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Puttu",
	"description" : "Puttu means portioned in Malayalam. It is made of steamed cylinders of ground rice layered with coconut shavings, sometimes with a sweet or savory filling on the inside",
	"description2" : "This is an Indian Dish",
	"price" : 4.4,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi2.wp.com%2Fwww.vegrecipesofindia.com%2Fwp-content%2Fuploads%2F2017%2F11%2Fputtu-recipe-1a.jpg&imgrefurl=https%3A%2F%2Fwww.vegrecipesofindia.com%2Fputtu-recipe%2F&tbnid=7zjDAeD3NSj45M&vet=12ahUKEwiB6ryss_HtAhWah0sFHYfmAxUQMygAegUIARDzAQ..i&docid=oS7j5s9hseo9QM&w=750&h=751&q=pics%20of%20puttu&ved=2ahUKEwiB6ryss_HtAhWah0sFHYfmAxUQMygAegUIARDzAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Appam",
	"description" : "Appam is a Nasrani dish of fermented bread made with rice batter and coconut milk. It is a staple diet and a cultural synonym of the Nasranis of Kerala, India. It is eaten most frequently for Breakfast or Dinner.",
	"description2" : "This is an Indian Dish",
	"price" : 4.3,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.cdnparenting.com%2Farticles%2F2020%2F04%2F08124906%2FAppam-Recipe.jpg&imgrefurl=https%3A%2F%2Fparenting.firstcry.com%2Farticles%2Fappam-recipe-toddlers%2F&tbnid=C5nCGUjn6sJqpM&vet=12ahUKEwjYmLqAtPHtAhWFFnIKHTVEAYgQMygBegUIARD4AQ..i&docid=WAHlIRjq171zdM&w=1024&h=700&q=pics%20of%20appam&ved=2ahUKEwjYmLqAtPHtAhWFFnIKHTVEAYgQMygBegUIARD4AQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Kothu parotta",
	"description" : "Kothu Parotta, a shredded flaky multi-layered Indian flatbread stir-fried with assorted vegetables/egg/chicken/lamb and essential spices. It is an incredibly popular street food in Tamil Nadu and Sri Lanka.",
	"description2" : "This is an Indian Dish",
	"price" : 4.7,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.hungryforever.com%2Fwp-content%2Fuploads%2F2015%2F04%2FFeatured-image-10-Chicken-65-Kothu-Parota.jpg&imgrefurl=https%3A%2F%2Fwww.hungryforever.com%2Frecipe%2Fchicken-65-kothu-parotta-recipe%2F&tbnid=RBAis5spXsuiQM&vet=12ahUKEwjnq_PZtPHtAhXJGHIKHZxwDWIQMygdegUIARDBAg..i&docid=u-4Q5O05AJJHoM&w=1200&h=630&q=pics%20of%20kothu%20parotta&ved=2ahUKEwjnq_PZtPHtAhXJGHIKHZxwDWIQMygdegUIARDBAg",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Idiyappam",
	"description" : "Idiyappam is a rice noodle dish originating from the Indian states of Kerala and Tamil Nadu and as well as from Sri Lanka. It consists of rice flour pressed into noodles, woven into a flat disc-like shape and steamed.",
	"description2" : "This is an Indian Dish",
	"price" : 4.2,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.awesomecuisine.com%2Fwp-content%2Fuploads%2F2008%2F02%2Fidiyappam.jpg&imgrefurl=https%3A%2F%2Fwww.awesomecuisine.com%2Frecipes%2F758%2Fidiyappam.html&tbnid=YcIKkCD_wKeKCM&vet=12ahUKEwiIwOeltfHtAhV-nksFHXDfCZIQMygIegUIARDyAQ..i&docid=T2Zg2w2bByEkBM&w=1067&h=600&q=pics%20of%20idiyappam&ved=2ahUKEwiIwOeltfHtAhV-nksFHXDfCZIQMygIegUIARDyAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Adai",
	"description" : "Adai is a stomach filling as it is a multi lentil crepe which is made with a mixture of four healthy dals/ lentils like the chana dal, moong dal, tur dal and urad dal, spiced with dry red chillies and fresh peppercorns.",
	"description2" : "This is an Indian Dish",
	"price" : 4.1,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F9c%2F83%2Ff4%2F9c83f4fb81211fb8b77ab38b52c9afa4.jpg&imgrefurl=https%3A%2F%2Fin.pinterest.com%2Fpin%2F540643130244137653%2F&tbnid=GVow5F285RKQEM&vet=12ahUKEwjdnJectvHtAhVmxnMBHY0eDE8QMygsegUIARDFAg..i&docid=ApNxe0Rh7P3adM&w=500&h=642&q=pics%20of%20adai&ved=2ahUKEwjdnJectvHtAhVmxnMBHY0eDE8QMygsegUIARDFAg",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Dosa / Idli",
	"description" : "A dosa is a rice pancake, originating from South India, made from a fermented batter predominantly consisting of lentils and rice. Idli is a type of savoury rice cake, originating from the Indian subcontinent, The cakes are made by steaming a batter",
	"description2" : "This is an Indian Dish",
	"price" : 3.8,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2F3.bp.blogspot.com%2F-C70NwP97VHE%2FUuNS3hdh-9I%2FAAAAAAAAYO8%2FLjseLo-lyso%2Fs600%2Fidli%2Cdosa%2Bplate.jpg&imgrefurl=https%3A%2F%2Fwww.chitrasfoodbook.com%2F2009%2F01%2Fidly-with-tomato-sambhar.html&tbnid=aEPIiCjO7c1kyM&vet=12ahUKEwi-qoWCt_HtAhWRW3wKHYKoDBsQMygMegUIARCIAg..i&docid=GbFoMeEnRrDXFM&w=500&h=501&q=pics%20of%20idli%20and%20dosa&ved=2ahUKEwi-qoWCt_HtAhWRW3wKHYKoDBsQMygMegUIARCIAg",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "nonveg",
	"name" : "Roti + Butter chicken /panner butter",
	"description" : "Butter chicken curry or murg makhani is a curry of chicken in a spiced tomato, butter and cream sauce. Paneer Butter Masala is a slightly sweet creamy dish of paneer, in which the gravy is prepared usually with butter, tomatoes, cashews or cream.",
	"description2" : "This is an Indian Dish",
	"price" : 4.5,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F53205522.cms%3Fimgsize%3D302803%26width%3D800%26height%3D800&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fbutter-chicken%2Frs53205522.cms&tbnid=x0erbBFQnpri4M&vet=12ahUKEwiP_eHEsfHtAhXDwHMBHf6ZAHEQMygAegUIARDuAQ..i&docid=gn80RtjETPAjDM&w=800&h=800&q=pics%20of%20butter%20chicken%20masala&ved=2ahUKEwiP_eHEsfHtAhXDwHMBHf6ZAHEQMygAegUIARDuAQ",
},
{
	"category1" : "Normal Dishes",
	"category2" : "Dinner",
	"category3" : "veg",
	"name" : "Roti + Panner Butter",
	"description" : "Paneer Butter Masala is a slightly sweet creamy dish of paneer, in which the gravy is prepared usually with butter, tomatoes, cashews or cream.",
	"description2" : "This is an Indian Dish",
	"price" : 4.5,
	"mediaUrl" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F53098531.cms%3Fimgsize%3D246555%26width%3D800%26height%3D800&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fpaneer-butter-masala%2Frs53098531.cms&tbnid=muccZsp_Hi5T0M&vet=12ahUKEwiFvrHgsvHtAhW0n0sFHYq0Aa0QMygCegUIARD6AQ..i&docid=4yclBcIM-hT_OM&w=800&h=800&q=pics%20of%20paneer%20butter%20masala&ved=2ahUKEwiFvrHgsvHtAhW0n0sFHYq0Aa0QMygCegUIARD6AQ",
},

{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "veg",
	"name" : "Pizza",
	"description" : "Pizza is a savory dish of Italian origin consisting of a usually round, flattened base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients, which is then baked at a high temperature, traditionally in a wood-fired oven.",
	"description2" : "This is an Italian Dish",
	"price" : 4.2,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "veg",
	"name" : "Hukka Noodles",
	"description" : "Hakka noodles is a Chinese preparation where boiled noodles are stir fried with sauces and vegetables or meats. A hakka noodle is made from unleavened dough( rice or wheat flour) that is cooked in a boiling liquid",
	"description2" : "This is an Chineese Dish",
	"price" : 4.0,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "nonveg",
	"name" : "Burger",
	"description" : "American Dream",
	"description2" : "This is an American Dish",
	"price" : 4.2,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "veg",
	"name" : "Sushi",
	"description" : "Sushi is a traditional Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanying a variety of ingredients, such as seafood, often raw, and vegetables.",
	"description2" : "This is an Japaneese Dish",
	"price" : 4.0,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "nonveg",
	"name" : "Lasagna",
	"description" : "Lasagne, or the singular lasagna, is an Italian dish made of stacked layers of thin flat pasta alternating with fillings such as ragù (ground meats and tomato sauce) and other vegetables, cheese (which may include ricotta and parmesan), and seasonings and spices such as garlic, oregano and basil.",
	"description2" : "This is an Italian Dish",
	"price" : 4.0,
	"mediaUrl" : "https://images.app.goo.gl/EUVRLHReSiK8fQ5X9",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "nonveg",
	"name" : "Hyderabadi Chicken Biriyani",
	"description" : "Hyderabadi Biryani is characteristically distinct. The aroma, taste, tender meat, the Zaffran, everything gives it a distinguished appearance.",
	"description2" : "This is an Indian Dish",
	"price" : 4.9,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "nonveg",
	"name" : "Kebab",
	"description" : "Kebabs are various cooked meat dishes, with their origins in Middle Eastern cuisine.",
	"description2" : "This is an Arab Dish",
	"price" : 4.0,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "nonveg",
	"name" : "Vindaloo",
	"description" : "Vindaloo or vindalho is an Indian curry dish based on the Portuguese dish carne de vinha d'alhos which is popular in Goa, Vasai, the Konkan, Kerala and other parts of India. It is known globally in its British Indian form as a staple of curry house and Indian restaurant menus, and is often regarded as a fiery, spicy dish. It is usually made with pork, but can be made with beef, mutton, chicken, or tofu.",
	"description2" : "This is an Indian Dish",
	"price" : 4.3,
	"mediaUrl" : "#",
},
{
	"category1" : "Exotic Dishes",
	"category2" : "special",
	"category3" : "nonveg",
	"name" : "Nethili Fry",
	"description" : "Nethili Fish Fry",
	"description2" : "This is an Indian Dish",
	"price" : 4.5,
	"mediaUrl" : "#",
}
]
const connectionURL = "mongodb+srv://lartum:Lartum@cluster0.qij9g.mongodb.net"
const databaseName = "chef_at_home"

MongoClient.connect(connectionURL, {
    useNewUrlParser:true
    }, (error, client) =>{
    if(error) {
        return console.log('Unable to connect to Database')
    }
    const db = client.db(databaseName);
    
    db.collection('products').insertMany( products, (error, result) =>{
            if(error){
                console.log('Unable to connect to the database ', error)
            }
            console.log(result);
    })
})
